### ISSUE TITLE
Modales

### ISSUE THREAD

**Issue by castromaciel** [DanuVillaContini/AcademySchoolFront#12]
## Proceso

1. Abrir la aplicación en vista de dispositivo móvil
2. Iniciar sesión con super usuario
3. Dar click en el icono de **cambiar contraseña** o en **ascender**

## Resultado esperado

Se espera que el checkbox este a la par del label

## Resultado actual

Se presentan a una distancia considerable

## Captura

<img width="1004" alt="image" src="https://github.com/DanuVillaContini/AcademySchoolFront/assets/83432755/e524e211-3c12-48cb-9d31-ec3f17fe8c9b">

<img width="469" alt="image" src="https://github.com/DanuVillaContini/AcademySchoolFront/assets/83432755/ca83e02e-b3c7-46b4-9b2b-df4bda2acc08">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by MauricioPerezIsa** [comment]
https://github.com/DanuVillaContini/AcademySchoolFront/commit/cc0289f71813da8da2c2a40a07b8b2ef28236e4f

Agregado un estilo para solucionar el problema de la distancia entre el checkbox y el texto
