### ISSUE TITLE
Mobile - Edición de un usuario

### ISSUE THREAD

**Issue by castromaciel** [DanuVillaContini/AcademySchoolFront#13]
## Proceso

1. Abrir la aplicación en vista de dispositivo móvil.
2. Iniciar sesión con super usuario.
3. Dar click en editar un usuario.
4. No me redirige/ no muestra la edición.

## Resultado esperado

Al editar un usario, lo que se espera es que el formulario de edición aparezca en primer plano. Ya sea un popup/dialogo, o bien si se genera en pantalla, debería redirigir al usuario al mismo

## Resultado actual

Se da click en editar y da la sensación de que no se está accionando el botón.

## Captura

https://github.com/DanuVillaContini/AcademySchoolFront/assets/83432755/42afacca-db9d-44fa-9d6c-7bdcd76639c9

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by DanuVillaContini** [comment]
32003e8
9ccc477

Se cambio form de Actualizar datos, el cual estaba oculto y aparecia cuando se hacia click en dicho button "Actualizar", por un modal con tal form. Esto para solucionar el hecho de hacer scroll hasta lograr ubicar donde estaba el form.
