### ISSUE TITLE
Cargar un empleado

### ISSUE THREAD

**Issue by castromaciel** [DanuVillaContini/AcademySchoolFront#14]
## Proceso

1. Iniciar sesión con super usuario
2. Dar click en el botón **nuevo personal**
3. Diligenciar el formulario con el campo **correo electrónico** incorrecto

## Resultado esperado

Se espera que al intentar registrar un usuario, y este haya diligenciado campos no esperados (O incorrectos) se le informe cómo deberían ser estos campos. 

En este caso en particular, el correo no era válido

## Resultado Actual

Da un error general, sin brindar mayor información

## Captura

<img width="883" alt="image" src="https://github.com/DanuVillaContini/AcademySchoolFront/assets/83432755/20260974-75b3-40f7-8179-a611e54c3596">

<img width="885" alt="image" src="https://github.com/DanuVillaContini/AcademySchoolFront/assets/83432755/d1b9e20d-65a4-4bc0-b682-4f0fb6a28d86">

<img width="894" alt="image" src="https://github.com/DanuVillaContini/AcademySchoolFront/assets/83432755/346a23d5-53ba-4bf8-8a1d-dcd32b5aceb8">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by MauricioPerezIsa** [comment]
https://github.com/DanuVillaContini/AcademySchoolFront/tree/1a5d67dbd31f1b5bcd4fc36f2633b061250096bc

https://github.com/DanuVillaContini/AcademySchoolFront/commit/1be8b1c127a2f44cdec08fad3278a966180001be

Descripción: Se eliminó la alerta. Se creo un objeto Errores que maneje el estado de los errores en cada campo del formulario y  el cual se implementó dentro de las funciones handleSubmit y handleUpdate, en las cuales estarán definidos los mensajes de errores en los campos a validar
Se crearon estilos condicionales para cambiar el color en el campo en el caso de que contenga un error.
