### ISSUE TITLE
Cambio de contraseña

### ISSUE THREAD

**Issue by castromaciel** [DanuVillaContini/AcademySchoolFront#15]
## Proceso

1. Iniciar sesión con un usuario con rol admin.
2. Realizar un cambio de clave.

## Resultado esperado

Al cambiar la contraseña, lo ideal es que se informe si la acción tuvo éxito o no. (Toast, Dialog, Popup).

## Resultado actual

Se realiza el cambio de clave pero no se informa el estado de la solicitud. Adicional, la contraseña ya actualizada persiste en el modal, aunque sea de un usuario diferente.

## Capturas

https://github.com/DanuVillaContini/AcademySchoolFront/assets/83432755/4bf48d73-e026-4c15-9109-6a23a656fa51

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by Pablocolombres** [comment]
corregido, se agregó ventana emergente para confirmar el cambio de contraseña en el commit "se agrega ventana modal para confirmar el cambio de pass"

**Comment by Pablocolombres** [comment]
https://github.com/DanuVillaContini/AcademySchoolFront/commit/d9e3a4be8aa77034b5fafda149a483b2b5eb614d

se corrige código de ventana emergente
