### ISSUE TITLE
Modal Actualizar nota

### ISSUE THREAD

**Issue by castromaciel** [DanuVillaContini/AcademySchoolFront#16]
## Proceso

1. Iniciar sesión con un usuario admin.
2. Ir a la sección de alumnos
3. Dar click en el icono de actualizar nota

## Resultado esperado

Si los campos obligatorios de un formulario no son diligenciados, se debe deshabilitar el botón para enviar la información al backend. Esto con el fin de no tener errores inesperados.

## Resultado actual

Se envía un formulario vacío y se muestran dos alertas con diferentes mensajes.

## Captura

https://github.com/DanuVillaContini/AcademySchoolFront/assets/83432755/efeafaf6-5005-4da6-9822-5fc4b5b60d13

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by DanuVillaContini** [comment]
https://github.com/DanuVillaContini/AcademySchoolFront/commit/f381aeaeee181c3537fde8be6ba3cbd4061aacae

f381aea

Se borro el alert que indicaba "Error al actualizar la nota", quedando un solo aviso cuando ocurre un error que impide tal operacion de actualizar. Y si evita el envio de un formulario vacio.
