### ISSUE TITLE
Uso incorrecto atributos en labels e inputs

### ISSUE THREAD

**Issue by castromaciel** [DanuVillaContini/AcademySchoolFront#17]
## Proceso

1. Iniciar sesión con super usuario
2. Dar click en el botón nuevo personal
3. Inspeccionamos el formulario

## Resultado esperado

Recordemos el uso del atributo htmlFor (for). El mismo va asociado a un id del input al que esté asociado.

Recordar también que los id son Identificadores únicos de cada elemento. No deberían haber dos ids iguales en la misma página.

## Resultado actual

Se tienen los mismo for e id para un formulario.

## Captura

<img width="1056" alt="image" src="https://github.com/DanuVillaContini/AcademySchoolFront/assets/83432755/dc566b0a-591a-45e2-a3c4-f0083a9fe79e">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by MauricioPerezIsa** [comment]
https://github.com/DanuVillaContini/AcademySchoolFront/commit/127074e51a37ad0e84a98b17227b849ea5e33c1c

Descripción: Se cambiaron todos los ID repetidos
